# WS_Samples.jl (TS)
# Wait-and-See: Solve TS samples from scratch for Transmission Switching
# This file solves each scenario from scratch and computes the average objective value.
#
# Usage:
#   julia WS_Samples.jl <instance_file> <samples_file>
#     instance_file: MATPOWER case file (e.g., case118Blumsack.m)
#     samples_file:  Path to TS samples file (e.g., Samples/TS/Scenarios/S25.txt)
#
# Output:
#   - Wait-and-see costs:  Samples/TS/Scenarios/WS<S>.txt
#   - (Optional extension later) Binary vectors could be saved similarly in Binary_vectors

using PowerModels
using JuMP, Gurobi
using MathOptInterface
const MOI = MathOptInterface
using DataFrames, XLSX, Random, Distributions
using Printf
using Statistics
using Dates

# Get project root for includes
script_dir = @__DIR__
project_root = dirname(dirname(script_dir))  # Samples/TS -> Samples -> project root

# Include utility functions and TS MILP from Heuristic code
include(joinpath(project_root, "Transmission_Switching", "Heuristic", "Candidate_List_Generation_Phase.jl"))
include(joinpath(project_root, "Transmission_Switching", "Heuristic", "Assignment_Phase.jl"))  # for load_samples_from_file

# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

function load_wait_and_see_costs_from_file(file_path::String)
    """Load wait-and-see costs from a file (TS version, same format as FL)."""
    if !isfile(file_path)
        error("❌ Error: Wait-and-see costs file not found! Expected: $file_path")
    end
    
    costs = Float64[]
    average_cost = Inf
    successful_solves = 0
    failed_solves = 0
    total_work_units = 0.0
    
    open(file_path, "r") do file
        for line in eachline(file)
            # Skip comments and empty lines
            if startswith(strip(line), "#") || strip(line) == ""
                # Try to extract metadata from comments
                if occursin("Average cost:", line)
                    match_result = match(r"Average cost: ([\d.]+|Inf)", line)
                    if match_result !== nothing
                        avg_str = match_result.captures[1]
                        if avg_str != "Inf"
                            average_cost = parse(Float64, avg_str)
                        end
                    end
                elseif occursin("Successful solves:", line)
                    match_result = match(r"Successful solves: (\d+)", line)
                    if match_result !== nothing
                        successful_solves = parse(Int, match_result.captures[1])
                    end
                elseif occursin("Failed solves:", line)
                    match_result = match(r"Failed solves: (\d+)", line)
                    if match_result !== nothing
                        failed_solves = parse(Int, match_result.captures[1])
                    end
                elseif occursin("Total work units:", line)
                    match_result = match(r"Total work units: ([\d.]+)", line)
                    if match_result !== nothing
                        total_work_units = parse(Float64, match_result.captures[1])
                    end
                end
                continue
            end
            
            # Parse cost value
            cost_str = strip(line)
            if cost_str == "Inf"
                push!(costs, Inf)
            else
                push!(costs, parse(Float64, cost_str))
            end
        end
    end
    
    return average_cost, costs, successful_solves, failed_solves, total_work_units
end

# =============================================================================
# MAIN FUNCTION: WAIT-AND-SEE COST COMPUTATION (TS)
# =============================================================================

function wait_and_see_cost(instance_file::String, samples_file::String;
                           log_dir::String="logs")
    """
    Compute wait-and-see cost by solving each TS scenario from scratch.
    
    Args:
        instance_file: MATPOWER case file (e.g., "case118Blumsack.m")
        samples_file: Path to file containing S samples (generated by Samples/TS/Samples.jl)
        log_dir: Directory for log files (under Samples/TS/)
    """
    println("="^80)
    println("WAIT-AND-SEE COST COMPUTATION - TRANSMISSION SWITCHING")
    println("="^80)
    println("Instance: $instance_file")
    println("Samples file: $samples_file")
    println("="^80)
    
    # Paths
    script_dir = @__DIR__
    project_root = dirname(dirname(script_dir))  # Samples/TS -> Samples -> root
    
    instance_path = joinpath(project_root, "Transmission_Switching", "instances", instance_file)
    
    # Resolve samples_file if relative
    if !isabspath(samples_file)
        if !isfile(samples_file)
            samples_file = joinpath(script_dir, "Scenarios", basename(samples_file))
        end
    end
    
    # Logs directory
    log_path = joinpath(script_dir, log_dir)
    if !isdir(log_path)
        mkpath(log_path)
        println("Created log directory: $log_path")
    end
    
    # Existence checks
    if !isfile(instance_path)
        error("❌ Error: Instance file not found! Expected: $instance_path")
    end
    if !isfile(samples_file)
        error("❌ Error: Samples file not found! Expected: $samples_file")
    end
    
    println("\n" * "="^40)
    println("STEP 1: LOADING DATA")
    println("="^40)
    
    # Extract case name and load network
    case_name = extract_case_name(instance_file)
    println("Extracted case name: $case_name")
    
    println("Loading network from: $instance_path")
    network = PowerModels.parse_file(instance_path)
    nb = length(network["bus"])
    nl = length(network["branch"])
    ng = length(network["gen"])
    println("✅ Network loaded: $nb buses, $nl branches, $ng generators")
    
    # Load samples
    println("\nLoading samples from: $samples_file")
    samples = load_samples_from_file(samples_file)
    S = length(samples)
    println("✅ Loaded $S samples")
    
    # Extract experiment type from samples filename
    # Supports:
    #   - S10_bernoulli.txt                  -> bernoulli
    #   - S10_case57_bernoulli.txt          -> bernoulli
    #   - S10_case118Blumsack_bernoulli.txt -> bernoulli
    # Falls back to "low" if pattern not matched.
    samples_basename = basename(samples_file)
    # Pattern 1: S<S>_<experiment_type>.txt
    # Pattern 2: S<S>_<case_name>_<experiment_type>.txt
    experiment_type = "low"  # default
    # Try to capture the last underscore-separated token before .txt as experiment type
    if occursin(r"^S\d+_.+\.txt$", samples_basename)
        # This regex captures everything after the last underscore up to .txt
        match_result = match(r"^S\d+_(?:.+_)?([^_]+)\.txt$", samples_basename)
        if match_result !== nothing && length(match_result.captures) == 1
            experiment_type = match_result.captures[1]
        end
    end
    println("✅ Experiment type: $experiment_type")
    
    println("\n" * "="^40)
    println("STEP 2: SOLVING SCENARIOS FROM SCRATCH")
    println("="^40)
    println("Solving each scenario from scratch...")
    
    # Timestamp for this run
    timestamp = Dates.format(now(), "YYYYmmdd_HHMMSS")
    
    costs = Float64[]                     # wait-and-see cost per scenario (may contain Inf)
    work_units_per_scenario = Float64[]   # work units per scenario (Inf for failed solves)
    binary_vectors = Vector{Vector{Int}}()  # store binary vectors from each scenario
    total_work_units = 0.0
    successful_solves = 0
    failed_solves = 0
    
    for (i, sample) in enumerate(samples)
        log_file = joinpath(log_path, "wait_and_see_scenario$(i)_$(timestamp).log")
        
        obj_value, binary_vector, penalty_flag, penalty_cost, work_units, theta_values =
            offline_calc_direct(network, sample, log_file)
        
        if obj_value != -1
            # Successful solve
            push!(costs, obj_value)
            push!(work_units_per_scenario, work_units)
            # store binary vector (convert to Int if needed)
            push!(binary_vectors, round.(Int, binary_vector))
            total_work_units += work_units
            successful_solves += 1
        else
            # Failed solve: mark cost and work units as Inf
            push!(costs, Inf)
            push!(work_units_per_scenario, Inf)
            # for failed solves, store empty vector placeholder
            push!(binary_vectors, Int[])
            failed_solves += 1
        end
        
        if i % 10 == 0
            println("  Processed $i scenarios")
        end
    end
    
    # Average over successful solves
    successful_costs = [c for c in costs if isfinite(c)]
    average_cost = length(successful_costs) > 0 ? mean(successful_costs) : Inf
    
    println("✅ Wait-and-see cost computation completed")
    println("   Total scenarios: $S")
    println("   Successful solves: $successful_solves")
    println("   Failed solves: $failed_solves")
    println("   Average wait-and-see cost: $(round(average_cost, digits=2))")
    println("   Total work units: $(round(total_work_units, digits=2))")
    println("   Log files stored in: $log_path")
    
    # Save per-scenario wait-and-see results to file: WS<S>_<experiment_type>.txt in Samples/TS/Scenarios
    scenarios_dir = joinpath(script_dir, "Scenarios")
    if !isdir(scenarios_dir)
        mkpath(scenarios_dir)
    end
    costs_file = joinpath(scenarios_dir, "WS$(S)_$(experiment_type).txt")
    
    open(costs_file, "w") do file
        println(file, "# scenario_index wait_and_see_cost work_units")
        for (i, cost) in enumerate(costs)
            wu = work_units_per_scenario[i]
            # Use \"Inf\" for infinite cost or work units (failed solves)
            cost_str = isfinite(cost) ? string(cost) : \"Inf\"
            wu_str = isfinite(wu) ? string(wu) : \"Inf\"
            println(file, \"$(i) $cost_str $wu_str\")
        end
        println(file, \"# summary: total_scenarios=$(S) successful=$(successful_solves) failed=$(failed_solves) total_work_units=$(total_work_units)\")
        println(file, \"# average_wait_and_see_cost=$(average_cost)\")
    end
    
    println("📁 Wait-and-see costs saved to: $costs_file")
    
    # Save binary vectors to: B<S>_<experiment_type>.txt in Samples/TS/Binary_vectors
    binary_vectors_dir = joinpath(script_dir, "Binary_vectors")
    if !isdir(binary_vectors_dir)
        mkpath(binary_vectors_dir)
    end
    binary_vectors_file = joinpath(binary_vectors_dir, "B$(S)_$(experiment_type).txt")
    
    open(binary_vectors_file, "w") do file
        # only save binary vectors corresponding to successful solves
        for (i, vec) in enumerate(binary_vectors)
            if !isempty(vec) && isfinite(costs[i])
                println(file, join(string.(vec), " "))
            end
        end
    end
    
    println("📁 Binary vectors saved to: $binary_vectors_file")
    println("   Total vectors saved: $successful_solves (only successful solves)")
    println("\n✅ Wait-and-see computation completed!")
    
    return average_cost, costs, total_work_units, successful_solves, failed_solves, costs_file, binary_vectors_file
end

# =============================================================================
# COMMAND-LINE INTERFACE
# =============================================================================

if abspath(PROGRAM_FILE) == @__FILE__
    if length(ARGS) < 2
        println("❌ Error: Incorrect number of arguments!")
        println("Usage: julia WS_Samples.jl <instance_file> <samples_file>")
        println("  instance_file: MATPOWER case file (e.g., case118Blumsack.m)")
        println("  samples_file: Path to file containing S samples (e.g., Samples/TS/Scenarios/S25.txt)")
        println("\nExample:")
        println("  julia WS_Samples.jl case118Blumsack.m Scenarios/S25.txt")
        exit(1)
    end
    
    instance_file = ARGS[1]
    samples_file  = ARGS[2]
    
    average_cost, costs, total_work_units, successful_solves, failed_solves, costs_file, binary_vectors_file =
        wait_and_see_cost(instance_file, samples_file)
    
    println("\n" * "="^80)
    println("TS WAIT-AND-SEE COST COMPUTATION COMPLETED")
    println("="^80)
    println("Average wait-and-see cost: $(round(average_cost, digits=2))")
    println("Successful solves: $successful_solves")
    println("Failed solves: $failed_solves")
    println("Cost results saved to: $costs_file")
    println("Binary vectors saved to: $binary_vectors_file")
end


